# Logging level: trace, debug, info, warn, error
log = "warn"

# Number of images to pre-cache in full view
window_size = 3

# Number of worker threads (0 = auto-detect CPUs)
threads = 0

# Background color in Hex
background = "#000000"

[bindings]
quit = "q"
toggle_fullscreen = "f"
switch_view_mode = "Escape"
switch_mouse_mode = "m"
grid_page_down = "PageDown"
grid_page_up = "PageUp"
reset_zoom = "z"
